import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/StoreProvider";
import { ConnectButton, ThirdwebProvider } from "thirdweb/react";
import { client } from "@/lib/client";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/root-components/Navbar";
import { lightTheme } from "thirdweb/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider>
          <StoreProvider>
            <img
              src="/blue.svg"
              alt="Blue"
              className="fixed -top-[50px] -left-[15px] z-[-100] animate-floatUp"
            />
            <img
              src="/green.svg"
              alt="green"
              className="fixed -bottom-[100px] -right-[150px] z-[-100] animate-floatDown"
            />
            <div className="fixed z-[100] top-3 right-3">
              <div className="flex justify-center mb-20 ">
                <ConnectButton
                  client={client}
                  theme={lightTheme({
                    colors: {
                      primaryButtonBg: "#ffffff",
                      primaryButtonText: "#000000",
                    },
                    
                  })}
                  connectModal={{ size: "wide" }}
                />
              </div>
            </div>
            <Toaster position="top-center" reverseOrder={false} />
            <div className="fixed top-0 left-0 w-full h-20">
              <Navbar />
            </div>
            <div className="py-24 px-36 min-h-screen">
              <div className="p-4 border-white/20 border-[1px] shadow-md  min-h-[calc(100vh_-_192px)] bg-[url('/glass.svg')] bg-cover bg-center bg-no-repeat rounded-[20px] backdrop-blur-2xl">
                {children}
              </div>
            </div>
          </StoreProvider>
        </ThirdwebProvider>
      </body>
    </html>
  );
}
